//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Settings/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Dev.Input
{
    public partial class @InputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""29defe18-3600-4e51-b5ff-c1fe812faf33"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""9682789f-15da-4d70-875e-9bb755ca12d4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Aiming"",
                    ""type"": ""Value"",
                    ""id"": ""b70cd21f-c19c-49fa-a877-419e0f5af5ac"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""7e1ea33a-c463-45eb-93e5-ce9a80095a1f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HerdState"",
                    ""type"": ""Button"",
                    ""id"": ""b0a48a9b-e091-4a9c-b642-a116a1009648"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HerdTarget"",
                    ""type"": ""Button"",
                    ""id"": ""0266c747-f9fb-4ad5-92af-89a17a146ff8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlingOrThrow"",
                    ""type"": ""Button"",
                    ""id"": ""d83f2647-332c-46cf-b0c9-2d74dc726ad2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""00df8dea-7879-4a60-8402-6af96e8bfa3a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bfe06cdd-e305-41e3-8d1e-4b4bcf19098b"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""Aiming"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""773fe9de-faa2-4ebb-a6d4-1ae36637e589"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""Aiming"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2353d175-f510-4532-998b-9906871521b8"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f9c47cb-e8f8-4484-8894-0927850dc284"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9599db7d-9d2f-4f32-9825-2b6f9dfe6075"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""HerdState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b995c4c4-7003-4926-9b84-9e6c84f380a3"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""HerdState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc6cf7ec-82b0-4077-b770-aa92783cc5af"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""HerdTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe5640ff-a6a7-442f-aa0e-f77caf818641"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""HerdTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""762f8975-e56f-467e-b4e0-e48517283cfb"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""SlingOrThrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc14be6d-c380-41b9-ad74-89af346213a5"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""SlingOrThrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""780e6312-411c-49f4-810a-370188be9934"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de8af37b-e2f2-4f4a-b374-777df65ca5e3"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12800e30-d1fe-4801-99b4-1b21ada1b09c"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD [Keyboard]"",
                    ""id"": ""7856cc7a-35e4-4751-b4c4-a26d3fc71a00"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7846e155-efdf-41bf-b562-a6fd1101c90d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3203f014-4516-4e8f-a827-a43a416f74fc"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""fcd46510-53c8-4360-b51f-978caf574025"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0450cbd1-d179-44f2-87cb-3c52e775b210"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""2c40f6d4-567b-4819-bb02-50c337249c06"",
            ""actions"": [
                {
                    ""name"": ""UI_Movement"",
                    ""type"": ""Value"",
                    ""id"": ""f226ce94-efa8-4433-9172-00c11c075505"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UI_Submit"",
                    ""type"": ""Button"",
                    ""id"": ""09238808-215c-4090-b124-c9a10076fd3a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UI_Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""a02e2600-3691-4ab2-bb46-5f6daa83c61a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a1d9dd03-74f2-4f52-a4a5-c99ff7fde5f0"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""UI_Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd51e42b-6751-4cf7-90ff-f9228108728d"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""UI_Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93cee4e4-85ca-4419-9d0e-48db5aa0f36b"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""UI_Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f2929bb-6475-41d2-83bc-c029df1d1379"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""UI_Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f34ca81a-e5da-4f50-a027-0c711a0358c7"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""UI_Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c97d2008-29b8-4e1b-8320-88cdceb251ee"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""UI_Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD [Keyboard]"",
                    ""id"": ""5c22e469-1e62-47f8-9999-427f44bd3175"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""75df921d-5182-45ee-9185-d3382a25b4e5"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""UI_Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a6decf05-3821-490e-8f4e-64bcbea03601"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""UI_Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""502c8e0f-487f-49af-861c-03d7cea182bb"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""UI_Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8908f633-b1af-4a34-9f67-1eca1f058fe2"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main scheme"",
                    ""action"": ""UI_Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Main scheme"",
            ""bindingGroup"": ""Main scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<DualShockGamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Gameplay
            m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
            m_Gameplay_Movement = m_Gameplay.FindAction("Movement", throwIfNotFound: true);
            m_Gameplay_Aiming = m_Gameplay.FindAction("Aiming", throwIfNotFound: true);
            m_Gameplay_Interact = m_Gameplay.FindAction("Interact", throwIfNotFound: true);
            m_Gameplay_HerdState = m_Gameplay.FindAction("HerdState", throwIfNotFound: true);
            m_Gameplay_HerdTarget = m_Gameplay.FindAction("HerdTarget", throwIfNotFound: true);
            m_Gameplay_SlingOrThrow = m_Gameplay.FindAction("SlingOrThrow", throwIfNotFound: true);
            m_Gameplay_Menu = m_Gameplay.FindAction("Menu", throwIfNotFound: true);
            // UI
            m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
            m_UI_UI_Movement = m_UI.FindAction("UI_Movement", throwIfNotFound: true);
            m_UI_UI_Submit = m_UI.FindAction("UI_Submit", throwIfNotFound: true);
            m_UI_UI_Cancel = m_UI.FindAction("UI_Cancel", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Gameplay
        private readonly InputActionMap m_Gameplay;
        private IGameplayActions m_GameplayActionsCallbackInterface;
        private readonly InputAction m_Gameplay_Movement;
        private readonly InputAction m_Gameplay_Aiming;
        private readonly InputAction m_Gameplay_Interact;
        private readonly InputAction m_Gameplay_HerdState;
        private readonly InputAction m_Gameplay_HerdTarget;
        private readonly InputAction m_Gameplay_SlingOrThrow;
        private readonly InputAction m_Gameplay_Menu;
        public struct GameplayActions
        {
            private @InputActions m_Wrapper;
            public GameplayActions(@InputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Movement => m_Wrapper.m_Gameplay_Movement;
            public InputAction @Aiming => m_Wrapper.m_Gameplay_Aiming;
            public InputAction @Interact => m_Wrapper.m_Gameplay_Interact;
            public InputAction @HerdState => m_Wrapper.m_Gameplay_HerdState;
            public InputAction @HerdTarget => m_Wrapper.m_Gameplay_HerdTarget;
            public InputAction @SlingOrThrow => m_Wrapper.m_Gameplay_SlingOrThrow;
            public InputAction @Menu => m_Wrapper.m_Gameplay_Menu;
            public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
            public void SetCallbacks(IGameplayActions instance)
            {
                if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
                {
                    @Movement.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMovement;
                    @Movement.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMovement;
                    @Movement.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMovement;
                    @Aiming.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAiming;
                    @Aiming.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAiming;
                    @Aiming.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAiming;
                    @Interact.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteract;
                    @Interact.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteract;
                    @Interact.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteract;
                    @HerdState.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnHerdState;
                    @HerdState.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnHerdState;
                    @HerdState.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnHerdState;
                    @HerdTarget.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnHerdTarget;
                    @HerdTarget.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnHerdTarget;
                    @HerdTarget.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnHerdTarget;
                    @SlingOrThrow.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSlingOrThrow;
                    @SlingOrThrow.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSlingOrThrow;
                    @SlingOrThrow.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSlingOrThrow;
                    @Menu.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMenu;
                    @Menu.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMenu;
                    @Menu.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMenu;
                }
                m_Wrapper.m_GameplayActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Movement.started += instance.OnMovement;
                    @Movement.performed += instance.OnMovement;
                    @Movement.canceled += instance.OnMovement;
                    @Aiming.started += instance.OnAiming;
                    @Aiming.performed += instance.OnAiming;
                    @Aiming.canceled += instance.OnAiming;
                    @Interact.started += instance.OnInteract;
                    @Interact.performed += instance.OnInteract;
                    @Interact.canceled += instance.OnInteract;
                    @HerdState.started += instance.OnHerdState;
                    @HerdState.performed += instance.OnHerdState;
                    @HerdState.canceled += instance.OnHerdState;
                    @HerdTarget.started += instance.OnHerdTarget;
                    @HerdTarget.performed += instance.OnHerdTarget;
                    @HerdTarget.canceled += instance.OnHerdTarget;
                    @SlingOrThrow.started += instance.OnSlingOrThrow;
                    @SlingOrThrow.performed += instance.OnSlingOrThrow;
                    @SlingOrThrow.canceled += instance.OnSlingOrThrow;
                    @Menu.started += instance.OnMenu;
                    @Menu.performed += instance.OnMenu;
                    @Menu.canceled += instance.OnMenu;
                }
            }
        }
        public GameplayActions @Gameplay => new GameplayActions(this);

        // UI
        private readonly InputActionMap m_UI;
        private IUIActions m_UIActionsCallbackInterface;
        private readonly InputAction m_UI_UI_Movement;
        private readonly InputAction m_UI_UI_Submit;
        private readonly InputAction m_UI_UI_Cancel;
        public struct UIActions
        {
            private @InputActions m_Wrapper;
            public UIActions(@InputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @UI_Movement => m_Wrapper.m_UI_UI_Movement;
            public InputAction @UI_Submit => m_Wrapper.m_UI_UI_Submit;
            public InputAction @UI_Cancel => m_Wrapper.m_UI_UI_Cancel;
            public InputActionMap Get() { return m_Wrapper.m_UI; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
            public void SetCallbacks(IUIActions instance)
            {
                if (m_Wrapper.m_UIActionsCallbackInterface != null)
                {
                    @UI_Movement.started -= m_Wrapper.m_UIActionsCallbackInterface.OnUI_Movement;
                    @UI_Movement.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnUI_Movement;
                    @UI_Movement.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnUI_Movement;
                    @UI_Submit.started -= m_Wrapper.m_UIActionsCallbackInterface.OnUI_Submit;
                    @UI_Submit.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnUI_Submit;
                    @UI_Submit.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnUI_Submit;
                    @UI_Cancel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnUI_Cancel;
                    @UI_Cancel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnUI_Cancel;
                    @UI_Cancel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnUI_Cancel;
                }
                m_Wrapper.m_UIActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @UI_Movement.started += instance.OnUI_Movement;
                    @UI_Movement.performed += instance.OnUI_Movement;
                    @UI_Movement.canceled += instance.OnUI_Movement;
                    @UI_Submit.started += instance.OnUI_Submit;
                    @UI_Submit.performed += instance.OnUI_Submit;
                    @UI_Submit.canceled += instance.OnUI_Submit;
                    @UI_Cancel.started += instance.OnUI_Cancel;
                    @UI_Cancel.performed += instance.OnUI_Cancel;
                    @UI_Cancel.canceled += instance.OnUI_Cancel;
                }
            }
        }
        public UIActions @UI => new UIActions(this);
        private int m_MainschemeSchemeIndex = -1;
        public InputControlScheme MainschemeScheme
        {
            get
            {
                if (m_MainschemeSchemeIndex == -1) m_MainschemeSchemeIndex = asset.FindControlSchemeIndex("Main scheme");
                return asset.controlSchemes[m_MainschemeSchemeIndex];
            }
        }
        public interface IGameplayActions
        {
            void OnMovement(InputAction.CallbackContext context);
            void OnAiming(InputAction.CallbackContext context);
            void OnInteract(InputAction.CallbackContext context);
            void OnHerdState(InputAction.CallbackContext context);
            void OnHerdTarget(InputAction.CallbackContext context);
            void OnSlingOrThrow(InputAction.CallbackContext context);
            void OnMenu(InputAction.CallbackContext context);
        }
        public interface IUIActions
        {
            void OnUI_Movement(InputAction.CallbackContext context);
            void OnUI_Submit(InputAction.CallbackContext context);
            void OnUI_Cancel(InputAction.CallbackContext context);
        }
    }
}
